# Generated by Django 3.0.8 on 2020-08-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagrabGellifiqueGelColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField()),
                ('username', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('caption', models.TextField()),
                ('like_count', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('media_type', models.IntegerField()),
                ('products', models.CharField(max_length=255)),
                ('created_dt', models.DateTimeField()),
                ('updated_dt', models.DateTimeField(blank=True, null=True)),
                ('code2', models.CharField(blank=True, max_length=100, null=True)),
                ('reposted_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instagrab_gellifique_gel_colour',
            },
        ),
    ]
